<?php $oNewsletterHelper = Mage::helper('sitewards_newsletter');?>
<form action="" id="checkout-agreements" onsubmit="return false;">
    <ol class="checkout-agreements">
        <?php foreach ($this->getAgreements() as $oAgreement): ?>
            <li>
                <div class="agreement-content"<?php echo ($oAgreement->getContentHeight() ? ' style="height:' . $oAgreement->getContentHeight() . '"' : '')?>>
                    <?php if ($oAgreement->getIsHtml()):?>
                        <?php echo $oAgreement->getContent() ?>
                    <?php else:?>
                        <?php echo nl2br($this->escapeHtml($oAgreement->getContent())) ?>
                    <?php endif; ?>
                </div>
                <p class="agree">
                    <input type="checkbox" id="agreement-<?php echo $oAgreement->getId()?>" name="agreement[<?php echo $oAgreement->getId()?>]" value="1" title="<?php echo $this->escapeHtml($oAgreement->getCheckboxText()) ?>" class="checkbox" />
                    <label for="agreement-<?php echo $oAgreement->getId()?>"><?php echo $oAgreement->getIsHtml() ? $oAgreement->getCheckboxText() : $this->escapeHtml($oAgreement->getCheckboxText()) ?></label>
                </p>
            </li>
        <?php endforeach ?>
        <?php if ($oNewsletterHelper->isSubscribed()): ?>
            <input type="hidden" name="is_subscribed" value="1" />
        <?php else: ?>
            <li>
                <input type="checkbox" id="is_subscribed" name="is_subscribed" value="1" title="<?php echo $oNewsletterHelper->__('I would like to be informed about the latest offers, promotions and news via e-mail. I can withdraw my consent at any time.') ?>" class="checkbox" />
                <label for="is_subscribed"><?php echo $oNewsletterHelper->__('I would like to be informed about the latest offers, promotions and news via e-mail. I can withdraw my consent at any time.') ?></label>
            </li>
        <?php endif; ?>
    </ol>
</form>